#spring.application.name=movieApi
#
#
#server.port=9292
#
#spring.datasource.url=jdbc:mysql://localhost:3306/movie?createDatabaseInfoNotExist=true
#spring.datasource.username=springstudent
#spring.datasource.password=springstudent
##spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
#spring.jpa.hibernate.ddl-auto=update
#
#logging.level.org.hibernate=info
#logging.level.org.hibernate.SQL=debug
#
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format-sql=true
#
#
#project.poster = poster/
#base.url="http://localhost:9292"




server:
  port: 9292
spring:
  datasource:
    username: springstudent
    password: springstudent
    url: jdbc:mysql://localhost:3306/movie
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: "Mohamed_Fathy"
    password: "0100084359260000"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

project:
  poster: posters/

base:
  url: "http://localhost:8080"
